#:schema node_modules/wrangler/config-schema.json
name = "multi-region-bucket-cloudflare-worker"
main = "src/index.js"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]

# account_id = "CLOUDFLARE_ACCOUNT_ID"

# IMPORTANT: ONLY FOR THE AUTH EXAMPLE
# [vars]
# UPSTASH_REDIS_REST_TOKEN = "REST_TOKEN"
# UPSTASH_REDIS_REST_URL = "REST_URL"

# IMPORTANT: YOU NEED TO EDIT THE "bucket_name" BASED ON WHAT YOU PUT ON CLOUDFLARE R2

[[r2_buckets]]
binding = "EEUR_BUCKET"
bucket_name = "EURR"

[[r2_buckets]]
binding = "WEUR_BUCKET"
bucket_name = "WEUR"

[[r2_buckets]]
binding = "ENAM_BUCKET"
bucket_name = "ENAM"

[[r2_buckets]]
binding = "WNAM_BUCKET"
bucket_name = "WNAM"

[[r2_buckets]]
binding = "APAC_BUCKET"
bucket_name = "APAC"